import { type ReactNode } from "react";
import { AlertTriangle } from "lucide-react";

export function ToolShell({
  title,
  description,
  icon,
  children,
}: {
  title: string;
  description: string;
  icon: ReactNode;
  children: ReactNode;
}) {
  return (
    <div className="mx-auto w-full max-w-6xl p-4 md:p-8">
      <header className="mb-6 flex items-start gap-4">
        <div
          className="grid h-12 w-12 shrink-0 place-items-center rounded-xl text-primary-foreground shadow-[var(--shadow-soft)]"
          style={{ background: "var(--gradient-brand)" }}
        >
          {icon}
        </div>
        <div className="min-w-0">
          <h1 className="truncate text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1>
          <p className="mt-1 text-sm text-muted-foreground">{description}</p>
        </div>
      </header>
      {children}
      <div className="mt-8 flex items-start gap-2 rounded-lg border border-border bg-muted/40 p-3 text-xs text-muted-foreground">
        <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        <p>
          Responsible AI: Outputs are generated by an AI model and may contain inaccuracies or
          biases. Review carefully before sending, sharing, or acting on the content. Do not paste
          sensitive personal data.
        </p>
      </div>
    </div>
  );
}